(define (make-queue )
    (let ((front-ptr '())
          (rear-ptr '()))
        (define (set-front-ptr! item)
            (set! front-ptr item))
        (define (set-rear-ptr! item)
            (set! rear-ptr item))
        (define (dispatch m)
            (cond ((eq? m 'front-ptr) front-ptr)
                  ((eq? m 'rear-ptr) rear-ptr)
                  ((eq? m 'set-front-ptr!) set-front-ptr!)
                  ((eq? m 'set-rear-ptr!) set-rear-ptr!)
                  (else (error "Unknown operation for QUEUE"))))
        dispatch))

