(define (make-monitored fn)
    (define call-count 0)
    (define (mf message)
        (cond ((eq? message 'how-many-calls) call-count)
              ((eq? message 'set-count) (set! call-count 0))
              (else (set! call-count (+ 1 call-count))
                    (fn message))))
    mf)

(define (make-account balance password)
    (define (deposit amount)
        (begin (set! balance (+ amount balance))
               balance))
    (define (withdraw amount)
        (if (>= balance amount)
            (begin (set! balance (- balance amount))
                   balance)
            (error "Insufficient balance")))
    (define wrong-pwd
        (make-monitored (lambda (x) (error "Incorrect password"))))
    (define (call-the-cops )
        (lambda (x) display "CALL-THE-COPS"))
    (define (dispatch pwd operation)
        (if (not (eq? pwd password))
            (if (= (wrong-pwd 'how-many-calls) 7)
                call-the-cops
                (wrong-pwd 'non-sense))
            (begin (wrong-pwd 'set-count)
                   (cond ((eq? operation 'withdraw) withdraw)
                         ((eq? operation 'deposit) deposit)
                         (else (error "Unknown operations"))))))
    dispatch)


(define acc (make-account 100 'secret-password))