(define (make-account balance password)
    (define (deposit amount)
        (begin (set! balance (+ amount balance))
               balance))
    (define (withdraw amount)
        (if (>= balance amount)
            (begin (set! balance (- balance amount))
                   balance)
            (error "Insufficient balance")))
    (define (dispatch pwd message)
        (if (not (eq? password pwd))
            (error "Incorrect password")
            (cond ((eq? message 'withdraw) withdraw)
                  ((eq? message 'deposit) deposit)
                  (else (error "Unknown operations")))))
    dispatch)

(define acc (make-account 100 'secret-password))

(define (make-joint account password new-password)
    (define (dispatch pwd message)
        (if (not (eq? pwd new-password))
            (error "Incorrect password")
            (cond ((eq? message 'withdraw) (account password message))
                  ((eq? message 'deposit) (account password deposit))
                  (else (error "Unknown operations")))))
    dispatch)